Page:
  extensions:
    - InsiteCommonPageExtension

PageController:
  extensions:
    - InsiteCommonPageControllerExtension

ListingHolder:
  extensions:
    - InsiteCommonListingExtension

ListingHolderController:
  extensions:
    - InsiteCommonListingControllerExtension
